---
title: "Outreach"
---

## Graduate Online Combinatorics Colloquium (GOCC) Organizer

I organize a weekly [online combinatorics seminar](https://sites.google.com/view/gocc-combinatorics/home?authuser=0) along with Dimitris Bogiokas, Mitsuki Hanada, and Joe McDonough. We'd love to see you!

## Directed Reading Program Mentorship

I served as a project mentor for the [Spelman-Morehouse Directed Reading Program (DRP)](https://sites.google.com/view/drp-hbcu/apply-to-the-drp) in the Spring of 2025. I worked with Sydni Jackson on the project "Symmetric functions: their combinatorics and applications," and we used [this wonderful text](https://bookstore.ams.org/view?ProductCode=STML/91) by Eric S. Egge. 

## Equity-focused teaching

I am passionate about cultivating mathematical enchantment in K-12 classrooms (and beyond) through inquiry-based pedagogy, and commited to [equity-focused teaching](https://crlt.umich.edu/equity-focused-teaching) practices and inclusive excellence. I am currently working toward the [U-M Graduate Teacher Certificate](https://crlt.umich.edu/um.gtc).

## Association for Women in Mathematics (AWM)

I manage the website of the [University of Michigan's Association for Women in Mathematics (AWM)](https://sites.google.com/umich.edu/awm/home). Check out our events and activities!

## Art of Problem Solving (AoPS Online)

Since July 2021, I have served as a grader for the online math community [Art of Problem Solving](https://artofproblemsolving.com/?srsltid=AfmBOophFh992JSR76haboaM4mfXuVtv1VoqLLpSkA-d5hGXDX1gnp-P). In this role, I provide guidance, mentorship, and personalized feedback on written homework to students of rigorous math courses to sharpen proof-writing and stimulate critical thinking.

