## Pre-prints

(@) **B. Zacovic**, B. Betti, V. Borovik, B. Finkel, and B. Sturmfels, Graphical Scattering Equations. [Preprint arXiv:2511.07316v2](https://arxiv.org/abs/2511.07316) (2025).

## Journal publications
(@) **B. Zacovic**, J. Koefler, U. Oktem, S. Paranjape, and J. Trnka, “Uniqueness of MHV Gravity Amplitudes.” *Le Matematiche*, Vol. 80 No. 1 (2025) 
[https://lematematiche.dmi.unict.it/index.php/lematematiche/article/view/2743](https://lematematiche.dmi.unict.it/index.php/lematematiche/article/view/2743).
(@) **B. Zacovic**, M. Cho, A. Dochtermann, R. Inagaki, S. Oh, and D. Snustad, “Chip-Firing
and Critical Groups of Signed Graphs.” *SIAM Journal on Discrete Mathematics*, Vol. 39, Iss. 2 (2025) 
[https://epubs.siam.org/doi/abs/10.1137/24M1655287?journalCode=sjdmec](https://epubs.siam.org/doi/abs/10.1137/24M1655287?journalCode=sjdmec).
(@) **B. Zacovic**, D. Galvin, and G. Wesley, "Enumerating Threshold Graphs and Some Related GraphClasses.” *Journal of Integer Sequences*, Vol. 25. (2022) 
[https://cs.uwaterloo.ca/journals/JIS/VOL25/Galvin/galvin2.pdf](https://cs.uwaterloo.ca/journals/JIS/VOL25/Galvin/galvin2.pdf).

## Posters and presentations
(@) [Chip-firing](./assets/Chip-firing poster.pdf)
(@) [The matroid complex and its homology](./assets/The matroid complex and its homology.pdf)
(@) [The hook length formula](./assets/Hook length formula.pdf)
(@) [MHV gravity amplitudes](./assets/MHV Gravity.pdf)

## Various notes
(@) [Algebra II University of Michigan QR Study Guide](./assets/Algebra II QR Exam Guide.pdf)
(@) [Lie Groups and Lie Algebras](./assets/Lie Groups & Lie Algebras.pdf)
(@) [Sard's Theorem](./assets/Sard's Theorem.pdf)







